/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fmcomms5_source.h)                                         */
/* BINDTOOL_HEADER_FILE_HASH(6b5c12b05d72e8ddb0a58a0e51c47c59)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/carbon/fmcomms5_source.h>
#include <rwt/rwt_base_block.h>
// pydoc.h is automatically generated in the build directory
#include <fmcomms5_source_pydoc.h>

void bind_fmcomms5_source(py::module& m)
{

    using fmcomms5_source = gr::rwt::fmcomms5_source;
    using rwt_base_block = gr::rwt::rwt_base_block;


    py::class_<fmcomms5_source,
         rwt_base_block,
	     gr::sync_block,
         gr::block,
         gr::basic_block,
        std::shared_ptr<fmcomms5_source>>(m, "fmcomms5_source", D(fmcomms5_source))

        .def(py::init(&fmcomms5_source::make),
           py::arg("config"),
           py::arg("reg_base_addr"),
           py::arg("*filter"),
           py::arg("auto_filter"),
           py::arg("force_reload"),
           py::arg("buffer_size"),
           D(fmcomms5_source,make)
        )
        ;
}

